
version: '2'
services:
  frontend:
    build: frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src

  backend:
    build: backend/
    ports:
      - "3001:3001"
    volumes:
      - ./backend/src:/usr/src/app/src
    environment:
      - DEBUG=backend:*
      - MYSQL_USER=test
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=app

  mysql:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=test
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=app
